# This file is generated by rake. Do not edit.

# -*- encoding: utf-8 -*-

module FFI

  class StatFS::Struct < FFI::Struct
    layout :f_type, :int, 0,
    :f_bsize, :long, 8,
    :f_blocks, :long, 16,
    :f_bfree, :long, 24,
    :f_bavail, :long, 32,
    :f_files, :long, 40,
    :f_ffree, :long, 48,
    :f_fsid, :long, 56,
    :f_namelen, :int, 64,
    :f_frsize, :int, 72,
    :f_spare, [:int, 5], 88
  end


end
